class GAConfig:
    POPULATION_SIZE = 25
    NUM_GENERATIONS = 500
    MUTATION_PROBABILITY = 0.05
    CROSSOVER_PROBABILITY = 0.7
    MUTATION_GAUSSIAN_SIGMA = 0.1
    MUTATION_UNIFORM_LOW = -1.0
    MUTATION_UNIFORM_HIGH = 1.0
    CROSSOVER_ALPHA = 0.5
    
    # Evaluation settings
    SEEDS_PER_AGENT = 20
    MAX_STEPS = 1500
    FRAME_DELAY = 1.0 / 60.0

    # Agent settings
    NUM_NEAREST_ASTEROIDS = 8
    HIDDEN_LAYER_SIZE = 24
